stock_prices <- c(100, 150)
names(stock_prices) <- c("AAPL", "MSFT")
print(stock_prices)
attr(stock_prices,"names") <- c("Monkey", "Banana")
print(stock_prices)
x <- 1:6
print (x)
dim(x) <- c(3,2)
today <- Sys.Date()
print(today)
now <- Sys.time()
print(now)
typeof(today)
typeof(now)
attributes(today)
attributes(now)
class(today)
attributes(now)
print(today+180)
print(now+1)
print(today+2000)
print(now)
unclass(now)
attr(now,"tzone") <- "UTC"
print(now)
unclass(now)
attr(now,"tzone") <- "EST"
print(now)
